name:  dev_new_latest

env:
  LOGICAL_APP_NAME: dev_new_last_version # The app name all these SBOMs will be assosiated with
  APP_VERSION: 1.0.1 # The app version all these SBOMs will be assosiated with
  # SBOM Author meta data - Optional
  AUTHOR_NAME: Alona Dodukh
  AUTHOR_EMAIL: alona@thiscompany.com 
  AUTHOR_PHONE: 11-00-999
  # SBOM Supplier meta data - Optional
  SUPPLIER_NAME: Scribe-Security 
  SUPPLIER_URL: www.scribesecurity.com 
  SUPPLIER_EMAIL: info@scribesecurity.com
  SUPPLIER_PHONE: 001-001-0011
  # URL's for dev
  SCRIBE_URL: "https://airflow.dev.scribesecurity.com/"
  SCRIBE_LOGIN_URL: "https://scribe-hub-dev.us.auth0.com"
  SCRIBE_AUDIENCE: "api.dev.scribesecurity.com"

on: workflow_dispatch
  # push:
  #   tags:
  #     - "*"
  

jobs:
  # scribe-sign-verify:
  #   runs-on: ubuntu-latest
  build:
    runs-on: ubuntu-latest

    permissions:
        contents: read
        packages: write
        id-token: write
    
    steps:

      - uses: actions/checkout@v3
      
      - name: Generate signed SBOM for repo content
        uses: scribe-security/action-bom@dev
        with:
         target: 'git:.'
         scribe-enable: true
         scribe-login-url: https://$AUTH0_DOMAIN
         scribe-audience: $AUTH0_SCRIBE_SERVICE_AUDIENCE
         scribe-url: $SCRIBE_API_BASE_URI
         product-key: "Sprint_38"
         scribe-client-id: ${{ secrets.CLIENT_ID}}
         scribe-client-secret: ${{ secrets.CLIENT_SECRET}}
         format: attest
         # app-name: $LOGICAL_APP_NAME
         # app-version: $APP_VERSION
         product-version: "test_1_0_2"
         components: packages,files,dep
         author-name: $AUTHOR_NAME
         author-email: $AUTHOR_EMAIL
         author-phone: $AUTHOR_PHONE
         supplier-name: $SUPPLIER_NAME
         supplier-url: $SUPPLIER_URL
         supplier-email: $SUPPLIER_EMAIL 
         supplier-phone: $SUPPLIER_PHONE

      - name: Build the Docker image
          # run: docker build . -t ${{ github.repository }}:${{ github.sha }}
        run: |
            docker build -t my-image:latest .   

      - name: Generate signed SBOM for docker image
        uses: scribe-security/action-bom@dev
        with:
                # target: 'docker:${{ github.repository }}:${{ github.sha }}'
                type: docker
                target: 'my-image:latest'
                scribe-enable: true
                product-key: "Sprint_38"
                scribe-client-id: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_ID }}
                scribe-client-secret: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_SECRET }}
                format: attest
                scribe-url: ${{ env.SCRIBE_URL }}
                scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
                scribe-audience: ${{ env.SCRIBE_AUDIENCE }}
                # app-name: $LOGICAL_APP_NAME
                # app-version: $APP_VERSION
                # author-name: $AUTHOR_NAME
                product-version: "test_1_0_2"
                author-email: $AUTHOR_EMAIL
                author-phone: $AUTHOR_PHONE
                supplier-name: $SUPPLIER_NAME
                supplier-url: $SUPPLIER_URL
                supplier-email: $SUPPLIER_EMAIL 
                supplier-phone: $SUPPLIER_PHONE
     
      # - name: Generate signed SBOM for docker image (bysybox)
      #   uses: scribe-security/action-bom@master
      #   with:
      #           # target: 'docker:${{ github.repository }}:${{ github.sha }}'
      #           type: docker
      #           target: 'busybox:1.35.0-glibc'
      #           scribe-enable: true
      #           product-key: "Sprint_38"
      #           scribe-client-id: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_ID }}
      #           scribe-client-secret: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_SECRET }}
      #           format: attest
      #           scribe-url: ${{ env.SCRIBE_URL }}
      #           scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
      #           scribe-audience: ${{ env.SCRIBE_AUDIENCE }}
      #           # app-version: $APP_VERSION
      #           # author-name: $AUTHOR_NAME
      #           product-version: "version_attest4_1"
      
      # - name: Generate signed SBOM for docker image (mongo-express:latest)
      #   uses: scribe-security/action-bom@master
      #   with:
      #           # target: 'docker:${{ github.repository }}:${{ github.sha }}'
      #           type: docker
      #           target: 'mongo-express:latest'
      #           scribe-enable: true
      #           product-key: "Sprint_38"
      #           scribe-client-id: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_ID }}
      #           scribe-client-secret: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_SECRET }}
      #           format: attest
      #           scribe-url: ${{ env.SCRIBE_URL }}
      #           scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
      #           scribe-audience: ${{ env.SCRIBE_AUDIENCE }}
      #           # app-version: $APP_VERSION
      #           # author-name: $AUTHOR_NAME
      #           product-version: "version_attest_1"
                
      
      # - name: Generate signed SBOM for docker image (mongo-express:0.54.0)
      #   uses: scribe-security/action-bom@master
      #   with:
      #           # target: 'docker:${{ github.repository }}:${{ github.sha }}'
      #           type: docker
      #           target: 'mongo-express:0.54.0'
      #           scribe-enable: true
      #           product-key: "Sprint_38"
      #           scribe-client-id: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_ID }}
      #           scribe-client-secret: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_SECRET }}
      #           format: attest
      #           scribe-url: ${{ env.SCRIBE_URL }}
      #           scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
      #           scribe-audience: ${{ env.SCRIBE_AUDIENCE }}
      #           # app-version: $APP_VERSION
      #           # author-name: $AUTHOR_NAME
      #           product-version: "1"
      
      - name: Generate SLSA provenance statement
        id: valint_slsa_statement
        uses: scribe-security/action-bom@dev
        with:
                # target: 'docker:${{ github.repository }}:${{ github.sha }}'
                type: docker
                target: my-image:latest
                # attest-slsa, statement-slsa
                format: statement-slsa
                product-key: "Sprint_38"
                product-version: "test_1_0_2"
                scribe-client-id: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_ID }}
                scribe-client-secret: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_SECRET }}
                scribe-url: ${{ env.SCRIBE_URL }}
                scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
                scribe-audience: ${{ env.SCRIBE_AUDIENCE }}
                

      - uses: actions/upload-artifact@v3
        with:
                name: provenance
                path: ${{ steps.valint_slsa_statement.outputs.OUTPUT_PATH }}
        

          

        # uses: scribe-security/action-verify@master
        # with:
        #   target: [target]
        #   format: [attest, statement, attest-slsa, statement-slsa, attest-generic, statement-generic]
        #   scribe-enable: true
        #   scribe-client-id: ${{ secrets.clientid }}
        #   scribe-client-secret: ${{ secrets.clientsecret }}
        #   app-name: $LOGICAL_APP_NAME
        #   app-version: $APP_VERSION
        #   author-name: $AUTHOR_NAME
        #   author-email: $AUTHOR_EMAIL
        #   author-phone: $AUTHOR_PHONE
        #   supplier-name: $SUPPLIER_NAME
        #   supplier-url: $SUPPLIER_URL
        #   supplier-email: $SUPPLIER_EMAIL 
        #   supplier-phone: $SUPPLIER_PHONE
